/**
 * @file      city_db.h
 * @brief     Shared city database: name, country, coordinates, timezone.
 *
 * One table for every app that needs to talk about places — the world clock
 * (name + timezone), weather (name + coordinates), GPS (nearest city) — so a
 * city is described once and they cannot disagree.
 *
 * city_db.c is GENERATED by tools/gen_city_db.py from tools/cities.txt; edit
 * the source list and regenerate rather than editing the C. Timezone strings
 * are pooled in city_zones[] because hundreds of cities share a handful of
 * them, and stored as POSIX TZ (understood by tzset) rather than IANA names,
 * which would need the full tzdata.
 *
 * Coordinates are hundredths of a degree, which keeps them in an int16 and is
 * good to about a kilometre — ample for a weather query or a 240 px map.
 */
#ifndef __CITY_DB_H__
#define __CITY_DB_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    const char *posix_tz;      /* e.g. "CET-1CEST,M3.5.0,M10.5.0/3" */
} city_zone_t;

typedef struct {
    const char *city;
    const char *country;
    int16_t     lat100;        /* degrees x100, north positive */
    int16_t     lon100;        /* degrees x100, east positive  */
    uint8_t     zone;          /* index into city_zones[]      */
} city_t;

extern const city_t      city_table[];
extern const int         city_count;
extern const city_zone_t city_zones[];
extern const int         city_zone_count;

static inline float city_lat(const city_t *c) { return c->lat100 / 100.0f; }
static inline float city_lon(const city_t *c) { return c->lon100 / 100.0f; }
static inline const char *city_tz(const city_t *c) { return city_zones[c->zone].posix_tz; }

/* Standard (non-DST) offset from UTC in minutes, derived from the POSIX
 * string. Computed rather than stored so the two can never disagree. */
int city_std_offset_min(const city_t *c);

/* Case-insensitive prefix match on city then country, for typeahead.
 * Returns how many pointers were written to `out`. */
int city_search_prefix(const char *prefix, const city_t **out, int max);

/* Cities whose standard offset matches, in table order. */
int city_in_zone(int offset_min, const city_t **out, int max);

/* Index of a city by exact name, or -1. Used to resolve saved selections. */
int city_index_of(const char *name);

/* Nearest city to a coordinate, or NULL if the table is empty. Lets GPS and
 * weather label a position without a network round trip. */
const city_t *city_nearest(float lat, float lon);

/* Distinct standard offsets present, ascending. Returns how many were written. */
int city_zone_offsets(int16_t *out, int max);

/* Format an offset as "UTC+08:00" / "UTC-03:30". */
void city_format_offset(int offset_min, char *out, int cap);

#ifdef __cplusplus
}
#endif

#endif /* __CITY_DB_H__ */
